### ISSUE TITLE
Maven Install Command not reading commandline parameters

### ISSUE THREAD

**Issue by heyitsaakash** [apigee/apigee-deploy-maven-plugin#135]
Hi,

i am trying to pass command line parameters as given i read me documentation -

mvn install -P test  -Dusername=$username  -Dpassword=$pwd -Dorg=$org

but it doesn't work when i hardcode the values in profile it works.

 <apigee.org>xxaws-eval</apigee.org>
                <apigee.username>xs@gmail.com</apigee.username>
                <apigee.password>$34</apigee.password> 

THiis is the error i am getting - 

```
POST  https://api.enterprise.apigee.com/v1/organizations/%7Borg%7D/apis?action=import&name=Mock-v1&validate=true
accept: [application/json]
accept-encoding: [gzip]
authorization: [Basic [Not shown in log]
content-type: application/octet-stream
 [Request body contains data, not shown] 

[ERROR] 401 Unauthorized
com.google.api.client.http.HttpResponseException: 401 Unauthorized
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1070)
	at io.apigee.buildTools.enterprise4g.rest.RestClient.executeAPI(RestClient.java:162)
	at io.apigee.buildTools.enterprise4g.rest.RestClient.uploadBundle(RestClient.java:426)
	at io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.execute(DeployMojo.java:72)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.246 s
[INFO] Finished at: 2020-06-23T12:23:58+05:30
[INFO] Final Memory: 17M/203M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.2.1:deploy (deploy-bundle) on project mock: 401 Unauthorized -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
aakas
```

Is there anything i am missing or is it an issue here..

thanks,
Aakash

**Comment by ssvaidyanathan** [comment]
@heyitsaakash - it could be due to the special character in your password (if you have them). I can think of two options

1. Pass your password within quotes - `mvn clean install -Ptest -Dusername=xs@gmail.com -Dorg=xxaws-eval -Dpassword='$34'`. I think the `$` sign is breaking your password in your terminal
2. Create a `settings.xml` file in your $HOME/.m2 directory and in that file, pass your profile info. For example
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      http://maven.apache.org/xsd/settings-1.0.0.xsd">
<profiles>
        <profile>
                <id>test</id>
                <properties>
                        <org>xxaws-eval</org>
                        <env>test</env>
                        <username>xs@gmail.com</username>
                        <password>$34</password>
                </properties>
        </profile>
</profiles>
<activeProfiles>
        <activeProfile>test</activeProfile>
</activeProfiles>
</settings>
```
Once this is created, then you can just run `mvn clean install -Ptest` in your terminal. Maven will automatically pick the values from your settings.xml and pass it over to the actual plugin

**Comment by heyitsaakash** [comment]
Hi,

i am not able to resolve this.. with the inputs got the same error -

Strangely, in other project teams they are using a similar stucture.. the only change i could see is that the parent pom.xml was inside the gateway folder.

I got their sample proxy and executed the same command (where i got the error), and it ran and deployed successfully -  
mvn install  -Ptest  -Dusername=xxxx@gmail.com  -Dpassword=\$Shane1234 -Dorg=aakash-test-eval


I am getting this error even in samples folder of the plugin I cloned from this repo.

Has it got anything to do with some caching or some plugin interpreting values incorrectly please help.


thanks,
Aakash

**Comment by ssvaidyanathan** [comment]
@heyitsaakash - will need more info, can you run the command with "-X" to see the debug logs. Probably you will get more info. In your earlier post - `https://api.enterprise.apigee.com/v1/organizations/%7Borg%7D/apis?action=import&name=Mock-v1&validate=true`, the org name I see is `%7Borg%7D` ? Are you sure you are passing the org name correctly or in other words, in your pom file, when you pass the org as argument in the maven command -Dorg=aakash-test-eval, does your shared-pom.xml have `<apigee.org>${org}</apigee.org>` in the `test` profile

**Comment by heyitsaakash** [comment]
closing it problem was in the org being passed.

**Comment by alokji420** [comment]
I am facing similar issue while trying to deploy an api proxy using maven apigee plugin.

after running mvn install command getting below error.

**Comment by alokji420** [comment]
[INFO] --- apigee-enterprise:1.3.1:deploy (deploy-bundle) @ mock-pet-store ---
Request prepared for the server
 **************************
POST  http://11.22.130.55:8080/v1/organizations/enterprise/apis?action=import&name=mock-pet-store&validate=true
accept: [application/json]
accept-encoding: [gzip]
authorization: [Basic [Not shown in log]
content-type: application/octet-stream
 [Request body contains data, not shown]

401 Unauthorized
com.google.api.client.http.HttpResponseException: 401 Unauthorized
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1070) ~[google-http-client-1.22.0.jar:1.22.0]
        at io.apigee.buildTools.enterprise4g.rest.RestClient.executeAPI(RestClient.java:165) ~[apigee-edge-maven-plugin-1.3.1.jar:?]
        at io.apigee.buildTools.enterprise4g.rest.RestClient.uploadBundle(RestClient.java:429) [apigee-edge-maven-plugin-1.3.1.jar:?]
        at io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.execute(DeployMojo.java:76) [apigee-edge-maven-plugin-1.3.1.jar:?]
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101) [maven-core-3.9.9.jar:3.9.9]
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906) [maven-embedder-3.9.9.jar:3.9.9]
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283) [maven-embedder-3.9.9.jar:3.9.9]
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:206) [maven-embedder-3.9.9.jar:3.9.9]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:255) [plexus-classworlds-2.8.0.jar:?]
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:201) [plexus-classworlds-2.8.0.jar:?]
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:361) [plexus-classworlds-2.8.0.jar:?]
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:314) [plexus-classworlds-2.8.0.jar:?]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.400 s
[INFO] Finished at: 2025-04-18T18:43:14+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.3.1:deploy (deploy-bundle) on project mock-pet-store: 401 Unauthorized -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by alokji420** [comment]
1- I tried my username and password in '' but it didn't worked.
2- checked my org it is fine
3- profile is updated with password in .pom as well as in setting.xml

but still i m getting same error

**Comment by ssvaidyanathan** [comment]
Lets discuss in the other issue you opened
