### ISSUE TITLE
Proxy without Description causes NullPointerException

### ISSUE THREAD

**Issue by ericdahl** [apigee/apigee-deploy-maven-plugin#35]
If a proxy xml file is missing its `<Description>`, then the plugin will fail with a NullPointerException despite the fact that the Description is supposed to be optional [according to the documentation](http://apigee.com/docs/api-services/reference/api-proxy-configuration-reference)

This bug seems to be caused by this piece of code in [PackageConfigurer](https://github.com/apigee/apigee-deploy-maven-plugin/blob/master/src/main/java/io/apigee/buildTools/enterprise4g/utils/PackageConfigurer.java#L156):

``` java
javax.xml.xpath.XPathExpression expression = xpath.compile("/APIProxy/Description");

NodeList nodes = (NodeList) expression.evaluate(xmlDoc,
        XPathConstants.NODESET);

if (nodes.item(0).hasChildNodes()) {
    // sets the description to whatever is in the <proxyname>.xml file
    nodes.item(0).setTextContent(expression.evaluate(xmlDoc));
} else {
```

The stack trace (once I updated the code to include the exception cause):

```
$ mvn -X install ...
[ERROR] Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.0.2-SNAPSHOT:configure (configure-bundle) on project httpbin: null: MojoExecutionException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.0.2-SNAPSHOT:configure (configure-bundle) on project httpbin: null
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException
        at io.apigee.buildTools.enterprise4g.mavenplugin.ConfigureMojo.configurePackage(ConfigureMojo.java:125)
        at io.apigee.buildTools.enterprise4g.mavenplugin.ConfigureMojo.execute(ConfigureMojo.java:51)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at io.apigee.buildTools.enterprise4g.utils.PackageConfigurer.configurePackage(PackageConfigurer.java:161)
        at io.apigee.buildTools.enterprise4g.mavenplugin.ConfigureMojo.configurePackage(ConfigureMojo.java:119)
        ... 22 more
```

By the way, is there a reason why the plugin doesn't include a nested Exception cause when throwing `MojoExecutionException`s ? If it were included it would be easier to debug with maven's `-X` flag.

**Comment by ericdahl** [comment]
any feedback? it's been 8 months

**Comment by msadasivam** [comment]
Thanks @ericdahl for this effort. I am trying to bring this in.
       <URL>http://stubit.raremile.com/stub/1327983465012/devices</URL>

I have a really minor point. Can you please change this URL in the test API proxy to something else.

**Comment by ericdahl-shutterfly** [comment]
I've updated that (and squashed the fix) to use example.com. I only had used that URL because some other existing test case was referencing it in the `taskservice1.zip` file.

**Comment by ericdahl** [comment]
I've updated that (and squashed the fix) to use example.com. I only had used that URL because some other existing test case was referencing it in the `taskservice1.zip` file.

**Comment by msadasivam** [comment]
Enhanced the fix to the following,
        Node node = (Node) expression.evaluate(xmlDoc, XPathConstants.NODE);
        if (node == null) {
            Element root = xmlDoc.getDocumentElement();
            node = xmlDoc.createElement("Description");
            root.appendChild(node);
        }

This takes care of the scenario where Description element is absent.
