### ISSUE TITLE
Installing proxy with java resource file fails to deploy

### ISSUE THREAD

**Issue by kurt-kanaskie** [apigee/apigee-deploy-maven-plugin#47]
Related article on Apigee community: 
[Community article](https://community.apigee.com/questions/8773/error-when-importoverridevalidate-proxy-with-jar-r.html)

The proxy gets uploaded but fails to deploy with following error:
`POST  https://api.enterprise.apigee.com/v1/organizations/ORGNAME/environments/dev/apis/PROXYNAME-v1/revisions/2/deployments
accept: application/json
accept-encoding: gzip
authorization: Basic [Not shown in log]
[ERROR] 500 Server Error
{
  "code" : "messaging.runtime.CouldNotExtractJavaResource",
  "message" : "Could not extract the java resource hmac-edge-callout1.jar",
  "contexts" : [ ],
  "cause" : {
    "message" : "/var/tmp/hmac-edge-callout1.jar_tempResourceDir6768640312569901831.tmp/hmac-edge-callout1.jar (Is a directory)",
    "contexts" : [ ]
  }
}
`

Downloading the proxy bundle reveals that the size of the jar file grew from 7K to 11K.

Stack trace:
`
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.0.0:deploy (deploy-bundle-step) on project bankcard-v1: 
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: 
	at io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.processHelpfulErrorMessage(DeployMojo.java:343)
	at io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.execute(DeployMojo.java:328)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.io.IOException: com.google.api.client.http.HttpResponseException: 500 Server Error
{
  "code" : "messaging.runtime.CouldNotExtractJavaResource",
  "message" : "Could not extract the java resource hmac-edge-callout1.jar",
  "contexts" : [ ],
  "cause" : {
    "message" : "/var/tmp/hmac-edge-callout1.jar_tempResourceDir6768640312569901831.tmp/hmac-edge-callout1.jar (Is a directory)",
    "contexts" : [ ]
  }
}
	at io.apigee.buildTools.enterprise4g.rest.RestUtil.activateBundleRevision(RestUtil.java:641)
	at io.apigee.buildTools.enterprise4g.rest.RestUtil.refreshBundle(RestUtil.java:546)
	at io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.doRefreshBundle(DeployMojo.java:210)
	at io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.execute(DeployMojo.java:299)
	... 22 more
Caused by: com.google.api.client.http.HttpResponseException: 500 Server Error
{
  "code" : "messaging.runtime.CouldNotExtractJavaResource",
  "message" : "Could not extract the java resource hmac-edge-callout1.jar",
  "contexts" : [ ],
  "cause" : {
    "message" : "/var/tmp/hmac-edge-callout1.jar_tempResourceDir6768640312569901831.tmp/hmac-edge-callout1.jar (Is a directory)",
    "contexts" : [ ]
  }
}
`

**Comment by kurt-kanaskie** [comment]
Not an issue with Apigee, use of <filtering>false</filtering> in maven-resources-plugin fixed the issu.
