### ISSUE TITLE
Multibundle project - Usage of <skip> option for parent pom

### ISSUE THREAD

**Issue by gerazenobi** [apigee/apigee-deploy-maven-plugin#52]
I have created a multi api bundle project in order to automate the deployment of my APIs. In doing so, I took as example the [Apigee Grass project](https://github.com/apigee/grass).

The difference lies in that I have tried to eliminate any redundancies between the parent pom and the children pom files. Ideally the children pom files would be empty unless they had to override something in particular, while the parent pom would have all the build configuration (plugins, goals, executions) as this build process is going to be the same for all the modules (unless tailored for rare cases within the children poms).

Now, I tried to do this by putting all the build configuration in the parent pom with a particular detail that the _apigee-edge-maven-plugin_ for this module (the parent one) would have to be skipped as this is not a deployable bundle but just the aggregation specification and build configuration for all the children.
That said, the children poms would have to override this tiny piece so that it was not skipped.

Hence my pom files looked like this:

**Parent pom**

``` xml
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>my.company.com</groupId>
  <artifactId>parent-pom</artifactId>
  <packaging>pom</packaging>
  <version>1.0</version>
  <pluginRepositories>

  </pluginRepositories>
  <modules>
    <module>../child_1</module>
   <!--...-->
    <module>../child_n</module>
  </modules>

  <build>
    <plugins>

      <plugin>
        <artifactId>maven-clean-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <execution>
            <id>auto-clean</id>
            <phase>initialize</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.0.1</version>
        <executions>
          <execution>
            <id>copy-resources-step</id>
            <phase>package</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <!-- this is important -->
              <overwrite>true</overwrite>
              <!-- target -->
              <outputDirectory>${basedir}/target/apiproxy</outputDirectory>
              <resources>
                <resource>
                  <!-- source -->
                  <directory>apiproxy</directory>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>io.apigee.build-tools.enterprise4g</groupId>
        <artifactId>apigee-edge-maven-plugin</artifactId>
        <version>1.0.3</version>
        <configuration>
          <skip>true</skip> <!-- Use this module level config to skip module build. Make it true -->
        </configuration>
        <executions>
          <execution>
            <id>configure-bundle</id>
            <phase>package</phase>
            <goals>
              <goal>configure</goal>
            </goals>
          </execution>
          <execution>
            <id>deploy-bundle</id>
            <phase>install</phase>
            <goals>
              <goal>deploy</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>

</project>
```

**Any child pom**

``` xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>my.company.com</groupId>
    <artifactId>parent-pom</artifactId>
    <version>1.0</version>
    <relativePath>../parent-pom/pom.xml</relativePath>
  </parent>

  <modelVersion>4.0.0</modelVersion>
  <groupId>my.company.com</groupId>
  <artifactId>child_1</artifactId>
  <version>1.0</version>
  <name>child_1</name>
  <packaging>pom</packaging>

  <build>
    <plugins>

      <plugin>
        <groupId>io.apigee.build-tools.enterprise4g</groupId>
        <artifactId>apigee-edge-maven-plugin</artifactId>
        <configuration>
          <skip>false</skip> <!-- Use this module level config to skip module build. Make it true -->
        </configuration>
      </plugin>

    </plugins>
  </build>

</project>
```

This approach does not work as it seems that the _apigee-edge-maven-plugin_ is not skipped for the parent project/pom: so it tries to import/deploy something that it is not an API bundle causing the build to fail:

``` bash
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.261 s
[INFO] Finished at: 2016-08-16T10:24:29+12:00
[INFO] Final Memory: 13M/276M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.0.3:deploy (deploy-bundle) on project parent-pom: MojoExecutionException: 400 Bad Request
[ERROR] {
[ERROR] "code" : "messaging.config.beans.InvalidBundle",
[ERROR] "message" : "Bundle is invalid. Unable to read/find APIProxy contents",
[ERROR] "contexts" : [ ]
[ERROR] }
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.0.3:deploy (deploy-bundle) on project parent-pom:
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException:
        at io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.processHelpfulErrorMessage(DeployMojo.java:373)
        at io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.execute(DeployMojo.java:358)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.io.IOException: 400 Bad Request
{
  "code" : "messaging.config.beans.InvalidBundle",
  "message" : "Bundle is invalid. Unable to read/find APIProxy contents",
  "contexts" : [ ]
}
        at io.apigee.buildTools.enterprise4g.rest.RestUtil.uploadBundle(RestUtil.java:398)
        at io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.doImport(DeployMojo.java:159)
        at io.apigee.buildTools.enterprise4g.mavenplugin.DeployMojo.execute(DeployMojo.java:283)
        ... 22 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I worked around this problem by removing from the parent pom only the _apigee-edge-maven-plugin_ entire section and putting it in all the children poms. Even though that there is not as much redundancy it still feels strange/not good having to do this.

Is there something I am not doing properly when using this <skip> configuration property?

Thanks in advance.

**Comment by tmk92** [comment]
Even I'm getting the same error while I try to deploy multiple proxies in on Jenkins Build

@msadasivam @gerazenobi @earth2marsh @senthildk can you suggest the solution for this 

`Waiting for Jenkins to finish collecting data
[ERROR] Failed to execute goal io.apigee.build-tools.enterprise4g:apigee-edge-maven-plugin:1.0.3:deploy (deploy-bundle) on project parent-pom: MojoExecutionException: 400 Bad Request
[ERROR] {
[ERROR] "code" : "repository.cassandra.UnableToReadApiProxy",
[ERROR] "message" : "Unable to read/find APIProxy contents",
[ERROR] "contexts" : [ ]
[ERROR] }
[ERROR] -> [Help 1]`

**Comment by msadasivam** [comment]
@tmk92 can you open a separate issue and provide details of your pom config and what you are trying to achieve. Please include the version of the plugin.

**Comment by mikezerosix** [comment]
Is there really no <property> for skip ? 
So that we would not have to include the whole plugin boilerplate to every sub module ? 
So instead we could jsut do: 
```xml
    <properties>
        <apigee.skip>true</apigee.skip>
    </properties>
```

**Comment by ssvaidyanathan** [comment]
@mikezerosix - no, the plugin does not support that property. 

Why would you need it in each sub-module? You can just use the executions on the parent module

Also - would be great if you can open a new GitHub issue and reference this issue for your context and share more details on what you are trying to do.

**Comment by mikezerosix** [comment]
@ssvaidyanathan
Because if you build the multi module project from the root so that it would build all sub modules on one go, it will throw exception as there is nothing to package and deploy at the root. So we need to explicitly tell the root skip=true and every sub module to skip=false.  

```xml
        <modules>
           <module>1</module>
           <module>2</module>
           <module>3</module>
           <module>4</module>
           <module>5</module>       
       <modules>
            <plugin>
                <groupId>io.apigee.build-tools.enterprise4g</groupId>
                <artifactId>apigee-edge-maven-plugin</artifactId>
                <version>2.5.0</version>
                <configuration>
                    <skip>TRUE on parent and FALSE for every sub module</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>configure-bundle</id>
                        <phase>package</phase>
                        <goals>
                            <goal>configure</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>deploy-bundle</id>
                        <phase>install</phase>
                        <goals>
                            <goal>deploy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

```

Of course wecan hack your own "apigee" property, 
so the root has 

```xml
    <properties>
        <my.skip>true</my.skip>
    </properties>
        <modules>
           <module>1</module>
           <module>2</module>
           <module>3</module>
           <module>4</module>
           <module>5</module>       
       <modules>
            <plugin>
                <groupId>io.apigee.build-tools.enterprise4g</groupId>
                <artifactId>apigee-edge-maven-plugin</artifactId>
                <version>2.5.0</version>
                <configuration>
                    <skip>${my.skip}</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>configure-bundle</id>
                        <phase>package</phase>
                        <goals>
                            <goal>configure</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>deploy-bundle</id>
                        <phase>install</phase>
                        <goals>
                            <goal>deploy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

```
and then in sub moduels override that custom property for each sub module: 
```
    <properties>
        <my.skip>false</my.skip>
    </properties>
```
This works, but still it would be nicer if this was actual apigee plugin build-in property. Most other maven plugins that I have used, all have the <skip> as plugin property.  
  
```
    <properties>
        <apigee.skip>false</apigee.skip>
    </properties>
```
